
services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=example
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=1234
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LANG=C.UTF-8
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
    depends_on:
      - mysql
      - redis

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  mysql:
    image: mysql:8.0.34
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
    networks:
      - app-network
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d  # 容器啟動時自動執行初始化脚本
    ports:
      - "3307:3306"


  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - app-network
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge



