ting:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: mysql
    port: 3307
    database: mydb
    username: root
    password: 1234
  jwt:
    secret-key: mattwei
  alioss:
    endpoint: oss-ap-northeast-1.aliyuncs.com
    access-key-id: ENC(cx+vFNwzF6n1PyEUpkts7P19vj4m5nYAlO7utmztJzZgm1f+XOO9kw==)
    access-key-secret: ENC(IVGTzMZe44Wh4q5/DCx5ru0dFBbUpF0tHgXgyUf97gMcrEuHC0wpqQ==)
    bucket-name: ting-ordering-system
  redis:
    host: redis
    port: 6379
    password: 1230
    database: 2
