ting:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: mysql
    port: 3306
    database: mydb
    username: root
    password: 1234
  jwt:
    secret-key: hello
  alioss:
    endpoint: oss-ap-northeast-1.aliyuncs.com
    access-key-id: [你的阿里雲AccessKeyId]
    access-key-secret: [你的阿里雲AccessKeySecret]
    bucket-name: ting-ordering-system
  redis:
    host: redis
    port: 6379
    database: 2
