ting:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: mysql
    port: 3306
    database: mydb
    username: root
    password: 1234
  jwt:
    secret-key: mattwei
  alioss:
    endpoint: oss-ap-northeast-1.aliyuncs.com
    access-key-id: LTAI5t6wSXwf2ueMGgofS5iS
    access-key-secret: CmC6WjX7bgYYz5r1ODwEFqv1oGYiBn
    bucket-name: ting-ordering-system
  redis:
    host: redis
    port: 6379
    password: 1230
    database: 2