ting:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: mysql
    port: 3306
    database: mydb
    username: root
    password: 1234
  jwt:
    secret-key: mattwei
  alioss:
    endpoint: oss-ap-northeast-1.aliyuncs.com
    access-key-id: ENC(AoOhYvL7HBHtxp+M7tIfKItw1c3dEWs4ECOv7upPuL9+s8CSCNT/pQ==)
    access-key-secret: ENC(GA4c3af/+/+99wHv7qX0FaFMUz3/eMbvsxdVr7PT4AOCjDUlRfOWog==)
    bucket-name: ting-ordering-system
  redis:
    host: redis
    port: 6379
    password: 1230
    database: 2
