name: CI/CD Workflow

on:
  push:
    branches:
      - main # 監聽 main 分支的變動
  pull_request:
    branches:
      - main  # 監聽從其他分支的 PR 請求

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 檢出代碼
        uses: actions/checkout@v2
      
      - name: 設定 Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 設置 Docker Compose
        run: |
          docker-compose -f docker-compose.yaml build
      
      - name: 啟動服務
        run: |
          docker-compose -f docker-comopse.yaml up -d

