name: CI/CD Workflow

on:
  push:
    branches:
      - main # 監聽 main 分支的變動
  pull_request:
    branches:
      - main  # 監聽從其他分支的 PR 請求

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 檢出代碼
        uses: actions/checkout@v2

      - name: 設定 JDK 環境
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # 使用你需要的 Java 版本

      - name: 編譯 JAR 檔案
        run: |
          cd backend/ # 進入後端目錄
          ./mvnw clean package -DskipTests  # 這將使用 Maven 生成 JAR 檔案
      
      - name: 設定 Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 安裝 Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: 設置 Docker Compose
        run: |
          docker-compose -f docker-compose.yaml build
      
      - name: 啟動服務
        run: |
          docker-compose -f docker-comopse.yaml up -d

